version: '3.8'

services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=grupo2
      - MINIO_ROOT_PASSWORD=admin123
      - MINIO_DEFAULT_BUCKETS=srag,ngl,vacinacao,srag-output,ngl-output,vacinacao-output

volumes:
  datasets: {}